---
## Create new project
### ansible-playbook -i inventories/dev/hosts  main.yaml   -CD

## Create new project and backup exist project ( exclude openshift- )
### ansible-playbook -i inventory onboarding.yaml -CD -t create,backup

## Only backup exist project ( exclude openshift-)
### ansible-playbook -i inventory onboarding.yaml -CD -t backup


- name: Openshift NSO Generator
  hosts: contabo
  serial: 1
#  connection: local
#  vars:
#      ansible_python_interpreter: /usr/bin/python3
  gather_facts: false
  roles:
    - role: install
      tags: never
    - role: configure
      tags: never
    - role: destroy
      tags: never
