- name: List keys or Objects
  amazon.aws.aws_s3:
    aws_access_key: d20c4bcbdbab4b23957323ed0d1f2af6
    aws_secret_key: 8ceed008d8422c6651e5c6a4b59e4fd3
    s3_url: https://eu2.contabostorage.com
    bucket: iso-image
    mode: list
  register: listresult
- debug: msg={{listresult.s3_keys}}


- name: Creating Space
  amazon.aws.aws_s3:
    aws_access_key: d20c4bcbdbab4b23957323ed0d1f2af6
    aws_secret_key: 8ceed008d8422c6651e5c6a4b59e4fd3
    s3_url: https://eu2.contabostorage.com
    bucket: iso-image
    mode: create
    rgw: True


- name: Simple PUT operation
  amazon.aws.s3_object:
    aws_access_key: d20c4bcbdbab4b23957323ed0d1f2af6
    aws_secret_key: 8ceed008d8422c6651e5c6a4b59e4fd3
    s3_url: https://eu2.contabostorage.com
    bucket: iso-image
    object: "{{ random_cluster_name | default(cluster_name) }}-rhcos-live.x86_64.iso"
    src: "{{ work_dir }}/rhcos-live.x86_64.iso"
    mode: put


- name: Upload/PUT file to S3 bucket
  community.aws.s3_sync:
    aws_access_key: d20c4bcbdbab4b23957323ed0d1f2af6
    aws_secret_key: 8ceed008d8422c6651e5c6a4b59e4fd3
    endpoint_url: https://eu2.contabostorage.com
    bucket: iso-image
    file_root: "{{ work_dir }}/rhcos-live.x86_64.iso"
  register: putresult


- name: Debug S3
  ansible.builtin.debug:
    msg: "{{ putresult }}"
    verbosity: 0
