
- name: Upload/PUT file to S3 bucket
  community.aws.s3_sync:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    endpoint_url : "{{ s3_url }}"
    bucket: "{{ bucket }}"
    file_root: "{{ work_dir }}/{{ random_cluster_name | default(cluster_name) }}-rhcos-live.x86_64.iso"
    permission: public-read
  register: putresult

- name: Debug S3
  ansible.builtin.debug:
    msg: "{{ putresult }}"
    verbosity: 0

- name: List keys or Objects
  amazon.aws.aws_s3:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    s3_url: "{{ s3_url }}"
    bucket: "{{ bucket }}"
    mode: list
  register: listresult

- name: Debug S3
  ansible.builtin.debug:
    msg: "{{ listresult }}"
    verbosity: 0

