- name: Login to an API
  ansible.builtin.uri:
    url: "{{  contabo_url }}"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{  contabo_username }}"
      password: "{{  contabo_password }}"
      grant_type: password
      client_id: "{{  contabo_client_id }}"
      client_secret: "{{  contabo_client_secret }}"
    status_code: 200
  register: contabo_login


- name: Set Access TOken 
  set_fact: 
    access_token: "{{ contabo_login.json.access_token }}"

- name: Set Session State
  set_fact: 
    session_state: "{{ contabo_login.json.session_state }}"


- name: Debug Contabo
  ansible.builtin.debug:
    msg: "{{ contabo_login }}"
    verbosity: 0
