- name: Get List Istance
  ansible.builtin.uri:
    url: https://api.contabo.com/v1/compute/instances
    method: GET
    body_format: form-urlencoded
    headers: 
      Authorization: Bearer {{ access_token }}
      x-request-id: "{{ session_state }}"
    body:
      grant_type: password
    status_code: 200
  register: contabo_vps_list


- name: Get instanceId
  set_fact: 
    instanceId: "{{ contabo_vps_list.json.data }}"


- name: Debug VPS list
  ansible.builtin.debug:
    msg: "{{ item.instanceId }}"
    verbosity: 3
  loop: "{{ instanceId  }}"



- name: Get List Image
  ansible.builtin.uri:
    url: https://api.contabo.com/v1/compute/images
    method: GET
    body_format: form-urlencoded
    headers: 
      Authorization: Bearer {{ access_token }}
      x-request-id: "{{ session_state }}"
    body:
      grant_type: password
    status_code: 200
  register: contabo_image_list


- name: Debug contabo_image_list
  ansible.builtin.debug:
    msg: "{{ item.name }}"
    verbosity: 0
  loop: "{{ contabo_image_list.json.data }}"


- name: Set imageId
  set_fact: 
    imageId: "{{ item.imageId }}"
  loop: "{{ contabo_image_list.json.data  }}"
  when: 
    - item.name == "{{ random_cluster_name | default(cluster_name) }}"

- name: Debug contabo_image_list
  ansible.builtin.debug:
    msg: "{{ imageId }}"
    verbosity: 0

- name: Set rootPassword
  set_fact: 
    rootPassword: "{{ lookup('community.general.random_string', length=10, upper=false, special=false) }}"


- name: Reinstall Specific Istance
  ansible.builtin.uri:
    url: "https://api.contabo.com/v1/compute/instances/{{ contabo_instanceId }}"
    method: PUT
    body_format: form-urlencoded
    headers: 
      Authorization: Bearer {{ access_token }}
      x-request-id: "{{ session_state }}"
    body:
      grant_type: password
      imageId: "{{ imageId }}"
    status_code: 200
  register: contabo_vps_list

